### ISSUE TITLE
سوال

### ISSUE THREAD

**Issue by ffarhadd** [dariubs/rtlmd#3]
سلام داداش خسته نباشی
من بخام توی پروژه های گیت ها و در فایل 
readme 
فارسی بنویسم چجوری باید اینکارو انجام بدم ؟ 
مرسی

**Comment by dariubs** [comment]
سلام. متاسفانه گیتهاب برای زبان‌های راست به چپ مثل فارسی از فرمت عمومی مارک‌داون پشتیبانی نمیکنه اما ازونجا که داخل مارک داون میتونید از تگهای اچ تی ام ال استفاده کنید میتونید با فرمت اچ تی ام ال بنویسید و استایل راست به چپ رو اینلاین استایل بدید به تگهاتون.

**Comment by ffarhadd** [comment]
اها. ممنونم
